# Use this Docker compose file to start an instance of Postgres that is required
# by the Kitty Items API.
#
# The Kitty Items marketplace uses Postgres to collect 'SaleOffer' events
# to display all sale listings on the marketplace page.

version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kittyitems
      - POSTGRES_USER=kittyuser
      - POSTGRES_PASSWORD=kittypassword
