version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kittyitems
      - POSTGRES_USER=kittyuser
      - POSTGRES_PASSWORD=kittypassword
  api:
    build: .
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "kitty-items-js/dist/index.js"]
    environment:
      - DATABASE_URL=postgresql://kittyuser:kittypassword@db:5432/kittyitems?sslmode=disable
      - FLOW_ACCESS_NODE=https://access-testnet.onflow.org
      - MIGRATION_PATH=kitty-items-js/dist/migrations
      - FUNGIBLE_TOKEN_ADDRESS=9a0766d93b6608b7
      - MINTER_ACCOUNT_KEY_IDX=0
      - MINTER_FLOW_ADDRESS=
      - MINTER_PRIVATE_KEY=
      - NON_FUNGIBLE_TOKEN_ADDRESS=
      - EVENT_SALE_OFFER_CREATED=
      - EVENT_SALE_OFFER_ACCEPTED=
      - EVENT_SALE_OFFER_FINISHED=
      - EVENT_COLLECTION_INSERTED_SALE_OFFER=
        EVENT_COLLECTION_REMOVED_SALE_OFFER=
    depends_on:
      - db
