version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kittyitems
      - POSTGRES_USER=kittyuser
      - POSTGRES_PASSWORD=kittypassword
  api:
    build: .
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "kitty-items-js/dist/index.js"]
    environment:
      - DATABASE_URL=postgresql://kittyuser:kittypassword@db:5432/kittyitems?sslmode=disable
      - FLOW_NODE=https://access-testnet.onflow.org
      - MIGRATION_PATH=kitty-items-js/dist/migrations
      - FUNGIBLE_TOKEN_ADDRESS=9a0766d93b6608b7
      - MINTER_ACCOUNT_KEY_IDX=0
      - MINTER_FLOW_ADDRESS=f087e28a6f37fe35
      - MINTER_PRIVATE_KEY=7ea81fe2335bc3b64f86361a26770251e4f3b055dba9929d976409c1a4a02978
      - NON_FUNGIBLE_TOKEN_ADDRESS=631e88ae7f1d7c20
      - SALE_OFFER_EVENT_NAME=A.f087e28a6f37fe35.KittyItemsMarket.SaleOfferCreated
    depends_on:
      - db
