version: "3"
services:
  web:
    profiles:
      - local
      - testnet
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile.web
    ports:
      - "3001:80"
    environment:
      - REACT_APP_CHAIN_ENV=${CHAIN_ENV}
      - REACT_APP_FLOW_ACCESS_API_URL=${ACCESS_API}
      - REACT_APP_WALLET_DISCOVERY=${WALLET_DISCOVERY}
      - REACT_APP_CONTRACT_FUNGIBLE_TOKEN=${FUNGIBLE_TOKEN_ADDRESS}
      - REACT_APP_CONTRACT_NON_FUNGIBLE_TOKEN=${NON_FUNGIBLE_TOKEN_ADDRESS}
      - REACT_APP_API_KIBBLE_MINT=${API_URL}/v1/kibbles/mint
      - REACT_APP_API_KITTY_ITEM_MINT=${API_URL}/v1/kitty-items/mint
      - REACT_APP_API_MARKET_ITEMS_LIST=${API_URL}/v1/market/latest
      - REACT_APP_CONTRACT_KIBBLE=${FLOW_ADDRESS}
      - REACT_APP_CONTRACT_KITTY_ITEMS=${FLOW_ADDRESS}
      - REACT_APP_CONTRACT_KITTY_ITEMS_MARKET=${FLOW_ADDRESS}
    depends_on:
      - api
      - db
  api:
    profiles:
      - local
      - testnet
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile.api
    ports:
      - "3000:3000"
    links:
      - "db:database"
    environment:
      - MINTER_ADDRESS=${FLOW_ADDRESS}
      - MINTER_PRIVATE_KEY=${FLOW_PRIVATE_KEY}
      - MINTER_ACCOUNT_KEY_INDEX=0
      - FUNGIBLE_TOKEN_ADDRESS=${FUNGIBLE_TOKEN_ADDRESS}
      - NON_FUNGIBLE_TOKEN_ADDRESS=${NON_FUNGIBLE_TOKEN_ADDRESS}
      - FLOW_ACCESS_API_URL=${ACCESS_API}
      - DATABASE_URL=database://kittyuser:kittypassword@localhost:5432/kittyitems
      - MIGRATION_PATH=./src/migrations
      - BLOCK_WINDOW=1
    depends_on:
      - db
  emulator:
    profiles:
      - local
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile.emulator
    ports:
      - "3569:3569"
      - "8080:8080"
  dev-wallet:
    profiles:
      - local
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile.wallet
    ports:
      - "8701:8701"
    environment:
      - FLOW_ACCESS_API_URL=${ACCESS_API}
      - FLOW_ACCOUNT_ADDRESS=${FLOW_ADDRESS}
      - FLOW_ACCOUNT_KEY_ID=0
      - FLOW_ACCOUNT_PRIVATE_KEY=${FLOW_PRIVATE_KEY}
      - FLOW_ACCOUNT_PUBLIC_KEY=${FLOW_PUBLIC_KEY}
    depends_on:
      - emulator
  db:
    profiles:
      - local
      - testnet
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kittyitems
      - POSTGRES_USER=kittyuser
      - POSTGRES_PASSWORD=kittypassword
