name: Kitty Items (local dev) Integrations Tests

on:
  pull_request:
    branches:
      - master

jobs:
  container-job:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_DB: kittyitems
    #       POSTGRES_USER: kittyuser
    #       POSTGRES_PASSWORD: kittypassword
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # - name: Install Typescript
      #   run: npm i -g next typescript ts-node-dev

      # - name: Install curl, git
      #   run: apt-get update && apt-get install curl git -y

      - name: Install flow-cli
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build & Run
        run: ./scripts/run-local.sh

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          record: false

      - name: Stop Containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
