name: Kitty Items (local dev) Integrations Tests

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install curl, git & Docker
        run: apt-get update && apt-get install curl git -y

      - name: Install flow-cli
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Install dependencies
        run: npx lerna exec npm install

      - name: Build & start containers
        run: ./srcipts/run-local.sh

      - name: Deploy contracts
        run: flow project deploy --network=emulator

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          record: false

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
